---
all:
  children:
    dns:
      hosts:
        infra-01:
          ansible_host: 192.168.68.14
          guest_hostname: infra-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    docker_hosts:
      hosts:
        infra-01:
          ansible_host: 192.168.68.14
          guest_hostname: infra-01
        docker-01:
          ansible_host: 192.168.68.21
          guest_hostname: docker-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    infisical:
      hosts:
        infra-01:
          ansible_host: 192.168.68.14
          guest_hostname: infra-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    object_storage:
      hosts:
        infra-01:
          ansible_host: 192.168.68.14
          guest_hostname: infra-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    gitlab:
      hosts:
        gitlab-01:
          ansible_host: 192.168.68.15
          guest_hostname: gitlab-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    runners:
      hosts:
        runner-01:
          ansible_host: 192.168.68.16
          guest_hostname: runner-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    dockhand_hosts:
      hosts:
        dockhand:
          ansible_host: 192.168.68.22
          guest_hostname: dockhand
          ansible_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python3

    portainer_hosts:
      hosts:
        portainer:
          ansible_host: 192.168.68.23
          guest_hostname: portainer
          ansible_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python3

    dockhand_agents:
      hosts:
        infra-01:
          ansible_host: 192.168.68.14
          guest_hostname: infra-01
        docker-01:
          ansible_host: 192.168.68.21
          guest_hostname: docker-01
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3

    k8s_control_plane:
      hosts:
        k8s-cp-01:
          ansible_host: 192.168.68.17
    k8s_workers:
      hosts:
        k8s-w-01:
          ansible_host: 192.168.68.18
          k8s_node_labels:
            workload: apps
        k8s-w-02:
          ansible_host: 192.168.68.19
          k8s_node_labels:
            workload: platform
        k8s-w-03:
          ansible_host: 192.168.68.20
          k8s_node_labels:
            workload: storage
    k8s_nodes:
      children:
        k8s_control_plane:
        k8s_workers:
      vars:
        ansible_user: nasr
        ansible_python_interpreter: /usr/bin/python3
